/*
 * P2PChat - Peer-to-Peer Chat Application
 *
 * Copyright (c) 2014 Ahmed Samy  <f.fallen45@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package p2pchat;

import java.io.IOException;

public class P2PChat extends javax.swing.JFrame
{
	private PeerNode node;
	public P2PChat()
	{
		try {
			node = new PeerNode(null, 9119);
			PeerNode p = new PeerNode(null, 9117);
			p.discoverPeers("localhost", 9118);
		} catch (IOException e) {
			e.printStackTrace();
		}

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents()
	{

		jScrollPane1 = new javax.swing.JScrollPane();
		chatText = new javax.swing.JTextArea();
		chatTextField = new javax.swing.JTextField();
		findPeersButton = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		chatParticipants = new javax.swing.JList();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		chatText.setEditable(false);
		chatText.setColumns(20);
		chatText.setRows(5);
		jScrollPane1.setViewportView(chatText);

		chatTextField.setText("Type here...");
		chatTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				chatTextFieldActionPerformed(evt);
			}
		});

		findPeersButton.setText("Find Peers");
		findPeersButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				findPeersButtonActionPerformed(evt);
			}
		});

		jScrollPane3.setViewportView(chatParticipants);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
		    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		    .addGroup(layout.createSequentialGroup()
		              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
		                        .addComponent(chatTextField)
		                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
		              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
		              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                        .addComponent(findPeersButton, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
		                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
		);
		layout.setVerticalGroup(
		    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
		    .addGroup(layout.createSequentialGroup()
		              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
		                        .addComponent(jScrollPane3))
		              .addGap(3, 3, 3)
		              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		                        .addComponent(chatTextField)
		                        .addComponent(findPeersButton, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void chatTextFieldActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_chatTextFieldActionPerformed
	{

	}//GEN-LAST:event_chatTextFieldActionPerformed

	private void findPeersButtonActionPerformed(java.awt.event.ActionEvent evt)  //GEN-FIRST:event_findPeersButtonActionPerformed
	{
		String[] peers = node.discoverPeers("localhost", 9118);
		if (peers != null) {
			for (String peer : peers)
				System.out.println(peer);
		} else {
			System.out.println("Failed to find any peers!");
		}
	}//GEN-LAST:event_findPeersButtonActionPerformed

	public static void main(String args[])
	{
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
			         | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(P2PChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new P2PChat().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JList chatParticipants;
	private javax.swing.JTextArea chatText;
	private javax.swing.JTextField chatTextField;
	private javax.swing.JButton findPeersButton;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane3;
	// End of variables declaration//GEN-END:variables
}
